### ISSUE TITLE
After  refresh the "Use product category" option value is set to "Use default" instead of "Use Product Category for contents"

### ISSUE THREAD

**Issue by benk21** [kathyisawesome/wc-mnm-categories#1]
In function additional_container_option(),
 
I think it should be,
**$mnm_product_object->get_meta( '_mnm_use_category' )**
not 
**$mnm_product_object->get_meta( '_mnm_use_categories' )**

It also need to update the js to trigger the change
$( "#mnm_product_data .mnm_use_category_field input" ).change();

**Comment by helgatheviking** [comment]
Closed by be9fecae1045332fb85bbfa8f581949383039397
